name: Tests

on: push

jobs:
  test:
    name: Test Layer contracts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: "Setup Node"
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - name: "Setup project"
        run: |
          yarn
      - name: "Run tests"
        run: |
          yarn suite:fork
